[package]
name = "cryptos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.16", features = ["derive", "env"] }
diesel = { version = "2.2.2", features = ["postgres"] }
dotenv = "0.15.0"
redis = "0.26.1"
redis-work-queue = "0.1.6"
rust_decimal = "1.35.0"
